### PR TITLE
 CA-268042: Update XenAPI bindings based on xen-api#6388e7710 and fix async interface

### LINKED ISSUE #52: References are just strings
Why does `VBD.create` from `xen-api-client` return a `string` instead of a VBD ref? :thinking_face: Noticed that this is true for all functions in `Xen_api_lwt_unix` - references are just strings.

### PR DESCRIPTION
**Pull request by mseri**
Bindings generated with

```
_build/default/ocaml/idl/ocaml_backend/gen_api_main.exe  -mode {api,client} -filterinternal true -filter closed
```
to make sure that the internal fields are filtered out.

This change fixes CA-268042 (see also #51)

This also includes updating the code to use Astring in place
of Stdext.Xstringext.

Fixes #52

### CODE REVIEW

**Comment by mseri** [comment]
Once approved and merged, this will require a new release of `xen-api-client` and the publication in `xs-opam`

**Comment by gaborigloi** [comment]
So you ran
```
_build/default/ocaml/idl/ocaml_backend/gen_api_main.exe  -mode api -filterinternal true -filter closed
_build/default/ocaml/idl/ocaml_backend/gen_api_main.exe  -mode client -filterinternal true -filter closed
```
to generate the required files?
Was just confused because first thought of how bash would expand `{api,client}`.

File: lib/aPI.ml [hunk 1]
```diff
@@ -22,9 +8,79 @@ include Rpc
 type string_list = string list [@@deriving rpc]
 
 module Ref = struct
-  type 'a t=string
-  let of_string x = x
+  (* BEGIN ref.ml from xen-api repository *)
```
Comment (gaborigloi) [inline lib/aPI.ml]: I think if we modified this after copying it from `xen-api` then we could mention it here, cause otherwise this comment can be a bit confusing:
`Modifications: replaced Stdext.Xstringext with Astring`

File: async/xen_api_async_unix.ml [hunk 2]
```diff
@@ -32,18 +32,16 @@ module IO = struct
...
 
-  let read =
-    let buf = String.create 4096 in
-    fun (_, ic) len ->
-      Reader.read ic ~len buf >>=
-      function
-      |`Ok len' -> return (String.sub buf 0 len')
-      |`Eof -> return ""
+  let read (_, ic) len =
+    let buf = Bytes.create len in
```
Comment (gaborigloi) [inline async/xen_api_async_unix.ml]: So the motivation for this change is to ensure that now different callers of the `read` function will not share the same buffer `buf`, but a new buffer will be created for each invocation?

File: async/xen_api_async_unix.ml [hunk 3]
```diff
@@ -32,18 +32,16 @@ module IO = struct
   let iter fn x = Deferred.List.iter x ~f:fn
 
   let read_line (_, ic) =
-    Reader.read_line ic >>=
-    function
-    |`Ok s -> return (Some s)
-    |`Eof -> return None
+    Reader.read_line ic
+    >>| function
```
Comment (gaborigloi) [inline async/xen_api_async_unix.ml]: Hmm, I know about `>|=`, but haven't seen this before :thinking:

File: lib/aPI.ml [hunk 4]
```diff
@@ -22,9 +8,79 @@ include Rpc
...
+      for i = 0 to 7 do Bytes.set r (i + 2) s.[prelen + i]; done;
+      for i = 0 to 3 do Bytes.set r (i + 10)  s.[prelen + 8 + 1 + i]; done;
+      r
+    with _ ->
+      s
+  (* END ref.ml from xen-api repository *)
+
   let rpc_of_t _ x = rpc_of_string (string_of x)
   let t_of_rpc _ x = of_string (string_of_rpc x);
 end
```
Comment (gaborigloi) [inline lib/aPI.ml]: Could we add a signature to it to fix #52 at the same time :smile: ? We can take the `ref.mli` from xen-api too I guess.

File: async/xen_api_async_unix.ml [hunk 5]
```diff
@@ -110,14 +108,12 @@ let do_it uri string =
...
-  let (>>=) = Deferred.(>>=) in
   let req = Xmlrpc.string_of_call call in
-  do_it uri req >>= fun x -> return (Xmlrpc.response_of_string x)
+  do_it uri req >>| Xmlrpc.response_of_string
 
 let make_json ?(timeout=30.) uri call =
-  let (>>=) = Deferred.(>>=) in
   let req = Jsonrpc.string_of_call call in
-  do_it uri req >>= fun x -> return (Jsonrpc.response_of_string x)
+  do_it uri req >>| Jsonrpc.response_of_string
```
Comment (gaborigloi) [inline async/xen_api_async_unix.ml]: Nice! I like these simplifications :)

File: lib/aPI.ml [hunk 6]
```diff
@@ -22,9 +8,79 @@ include Rpc
...
+  (* very ugly hack to be able to distinguish dummy and real tasks. Moreover, dummy tasks have their name *)
+  (* embedded into the reference .... *)
+  
+  (* a dummy reference is a reference of an object which is not in database *)
+  let dummy_sep = "|"
+  let dummy_prefix = "DummyRef:"
+  
+  
+  let make_dummy task_name =
+    let uuid = Uuidm.v `V4 |> Uuidm.to_string in
```
Comment (gaborigloi) [inline lib/aPI.ml]: So here we moved to `Uuidm` too - nice!

File: lib/aPI.ml [hunk 7]
```diff
@@ -22,9 +8,79 @@ include Rpc
...
+    try
+      let r = Bytes.create 14 in
+      Bytes.set r 0 c; Bytes.set r 1 ':';
+      for i = 0 to 7 do Bytes.set r (i + 2) s.[prelen + i]; done;
+      for i = 0 to 3 do Bytes.set r (i + 10)  s.[prelen + 8 + 1 + i]; done;
+      r
+    with _ ->
+      s
+  (* END ref.ml from xen-api repository *)
+
```
Comment (gaborigloi) [inline lib/aPI.ml]: This means we will have lots of useful functions available now, such as `Ref.really_pretty_and_small`, that weren't included in the `Ref` module `xen-api-client` before :).

File: lib/aPI.ml (hunk 4 above)
Comment (gaborigloi) [reply lib/aPI.ml]: Although it's also fine to do that separately.

File: lib/xen_api.ml [hunk 8]
```diff
@@ -113,18 +113,20 @@ module Make(IO:IO) = struct
         Response.read_body_chunk reader
         >>= function
         | Cohttp.Transfer.Chunk x ->
+          (* Printf.eprintf "Chunk: %s\n%!" x; *)
```
Comment (gaborigloi) [inline lib/xen_api.ml]: I assume we could remove these now that it works?

File: opam [hunk 9]
```diff
@@ -24,17 +24,18 @@ remove: [["ocamlfind" "remove" "xen-api-client"]]
...
-  "uri"
   "re"
-  "xmlm"
   "rpc" {>= "1.9.51"}
-  "xapi-rrd"
+  "ssl"
+  "uri"
   "uuidm"
+  "xapi-rrd"
+  "xmlm"
```
Comment (gaborigloi) [inline opam]: Nice, I like sorted lists, much easier to read and update! :D

File: lib/aPI.ml [hunk 10]
```diff
@@ -22,9 +8,79 @@ include Rpc
...
+  let cut_in_three ~sep str =
+    let (>>=) opt f =
+      match opt with
+      | Some value -> f value
+      | None -> None
+    in
+    let open Astring in
+    String.cut ~sep str
+    >>= fun (head, tail) ->
+      String.cut ~sep tail
```
Comment (gaborigloi) [inline lib/aPI.ml]: Very minor point, but is there a specific reason this code does not follow the usual indentation?:
```ocaml
    >>= fun (head', tail) ->
    Some (head, head', tail)
```

File: async/xen_api_async_unix.ml (hunk 2 above)
Comment (gaborigloi) [inline async/xen_api_async_unix.ml]: So this means that the buffer `buf` won't be shared any more between subsequent invocations of `read`, but a new one will be created each time we call it - is this the change that fixed the Async bindings?

File: lib/aPI.ml (hunk 6 above)
Comment (mseri) [reply lib/aPI.ml]: Yep, I'll expand the commit message

File: lib/xen_api.ml (hunk 8 above)
Comment (mseri) [reply lib/xen_api.ml]: No, I'd rather keep them for the next time :P

File: lib/aPI.ml (hunk 10 above)
Comment (mseri) [reply lib/aPI.ml]: Probably I forgot to ocp-indent it. I'll add a commit to fix indentation

File: async/xen_api_async_unix.ml (hunk 2 above)
Comment (mseri) [reply async/xen_api_async_unix.ml]: Yes

**Comment by mseri** [comment]
All valid points, I'll update it

File: lib/aPI.ml (hunk 7 above)
Comment (mseri) [reply lib/aPI.ml]: Yep

File: lib/aPI.ml (hunk 4 above)
Comment (mseri) [reply lib/aPI.ml]: I think it's worth it. Done.

Note that I had to fix a test, so it may break some code that relies on it being a string, but I'd rather fix that code

**Comment by mseri** [comment]
I did run ```
_build/default/ocaml/idl/ocaml_backend/gen_api_main.exe  -mode api -filterinternal true -filter closed
_build/default/ocaml/idl/ocaml_backend/gen_api_main.exe  -mode client -filterinternal true -filter closed
```

File: lib/aPI.ml (hunk 4 above)
Comment (gaborigloi) [reply lib/aPI.ml]: Yeah, it will probably break my code :rofl:
